# Generated by Django 6.1.1 on 2026-10-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facility_code', models.CharField(max_length=50, unique=True)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('HEALTH_CENTER', 'Health Center'), ('CLINIC', 'Clinic'), ('DISPENSARY', 'Dispensary'), ('LABORATORY', 'Laboratory'), ('PHARMACY', 'Pharmacy'), ('REFERRAL_CENTER', 'Referral Center'), ('OTHER', 'Other')], max_length=30)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('services', models.TextField(blank=True)),
                ('referral_available', models.BooleanField(default=True)),
                ('operating_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TEMPORARILY_CLOSED', 'Temporarily Closed')], default='ACTIVE', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('STAFF', 'Staff'), ('EQUIPMENT', 'Equipment'), ('BED', 'Beds'), ('MEDICINE', 'Medicine'), ('LABORATORY', 'Laboratory'), ('OTHER', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='FacilitiesApp.facility')),
            ],
        ),
    ]
