# Generated by Django 6.1.1 on 2026-09-22 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_type', models.CharField(choices=[('GENERAL', 'General Health'), ('INFECTIOUS', 'Infectious Disease'), ('AMR', 'Antimicrobial Resistance'), ('COMPREHENSIVE', 'Comprehensive')], default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed')], default='STARTED', max_length=20)),
                ('chief_complaint', models.TextField(blank=True)),
                ('screening_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_screenings', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='PatientsApp.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_screenings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=10)),
                ('recommended_action', models.TextField(blank=True)),
                ('ai_assisted', models.BooleanField(default=False)),
                ('clinician_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='ScreeningApp.screening')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('response_type', models.CharField(choices=[('TEXT', 'Text'), ('BOOLEAN', 'Yes/No'), ('NUMBER', 'Number'), ('CHOICE', 'Choice')], default='TEXT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ScreeningApp.screening')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
