# Generated by Django 6.1.1 on 2026-10-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FollowupsApp', '0001_initial'),
        ('PatientsApp', '0001_initial'),
        ('ReferralsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('REFERRAL_CREATED', 'Referral Created'), ('REFERRAL_UPDATED', 'Referral Updated'), ('REFERRAL_ACCEPTED', 'Referral Accepted'), ('REFERRAL_DECLINED', 'Referral Declined'), ('FOLLOW_UP_CREATED', 'Follow-up Created'), ('FOLLOW_UP_REMINDER', 'Follow-up Reminder'), ('FOLLOW_UP_COMPLETED', 'Follow-up Completed'), ('FOLLOW_UP_MISSED', 'Follow-up Missed'), ('AMR_ALERT', 'AMR Alert'), ('SYSTEM_ALERT', 'System Alert')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='FollowupsApp.followup')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='PatientsApp.patient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='ReferralsApp.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
