# Generated by Django 6.1.1 on 2026-10-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PatientsApp', '0001_initial'),
        ('ReferralsApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('REFERRAL_REVIEW', 'Referral Review'), ('TREATMENT_REVIEW', 'Treatment Review'), ('SCREENING_REVIEW', 'Screening Review'), ('AMR_REVIEW', 'AMR Review'), ('GENERAL_REVIEW', 'General Review')], default='GENERAL_REVIEW', max_length=20)),
                ('reason', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=15)),
                ('outcome', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='PatientsApp.patient')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='ReferralsApp.referral')),
            ],
        ),
    ]
