# Generated by Django 6.1.1 on 2026-09-24 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AIApp', '0001_initial'),
        ('PatientsApp', '0001_initial'),
        ('ScreeningApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Antibiotic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('antibiotic_class', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AMRRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure_history', models.TextField(blank=True)),
                ('infection_information', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('URGENT', 'Urgent')], max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amr_records', to='AIApp.aianalysis')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_amr_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amr_records', to='PatientsApp.patient')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amr_records', to='ScreeningApp.screening')),
            ],
        ),
        migrations.CreateModel(
            name='ResistanceTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('SUSCEPTIBLE', 'Susceptible'), ('INTERMEDIATE', 'Intermediate'), ('RESISTANT', 'Resistant'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=12)),
                ('test_notes', models.TextField(blank=True)),
                ('tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amr_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistance_tests', to='AmrApp.amrrecord')),
                ('antibiotic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resistance_tests', to='AmrApp.antibiotic')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resistance_tests', to='AmrApp.organism')),
            ],
        ),
    ]
